bto.sc=compile.model()
#fname="/home/ken/sports/sx.dat"
fname="/home/ken/teaching/stan/cfl.dat"
ans=run.rating(fname,bto.sc,0,T)
head(ans$tab)
ans$cc
ans$tab
ans$pred
pred(ans,1,1)
ng=0
xy=make.clean(fname,ng)
gc=game.count(xy$x)
gc
res=estimate(xy,bto.sc)
df=data.frame(team=names(res$beta),gc,elo.scale(res$beta))
