---
title: "Replace with Main Title"
author: "Your Name"
date: "AUTOMATIC"
---


```{r echo=FALSE, message=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```

```{r}
load("/home/ken/teaching/btstan/R/stuff.txt")
```

```{r}
load("/home/ken/teaching/btstan/R/xy.txt")
```


```{r}
load("/tmp/RtmpWIGVLY/xy")
```

```{r}
scatterplot(y~x, reg.line=FALSE, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  data=xy)
```

```{r}
with(xy, lineplot(x, y))
```

```{r}
scatterplot(y~x, reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots='xy', span=0.5, ellipse=FALSE, levels=c(.5, .9), data=xy)
```

```{r}
scatterplot(y~x, reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  data=xy)
```

```{r}
scatterplot(y~x, reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  data=xy)
```

```{r}
RegModel.1 <- lm(y~x, data=xy)
summary(RegModel.1)
```

```{r}
Anova(RegModel.1, type="II")
```

